// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class PlayerEconomyData
    {
        public Dictionary<string,int> Currencies;
        public Dictionary<string,int> ItemInventory;
        public bool HasPurchasedFreeCoinPack;
        public long InfiniteHeartsExpiryTimestamp;

        [Preserve]
        public PlayerEconomyData ()
        {
        }
    }
}