// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class DailyRewardsResult
    {
        public bool Success;
        public bool FirstVisit;
        public int DaysRemaining;
        public long SecondsTillClaimable;
        public long SecondsTillNextDay;
        public bool IsStarted;
        public bool IsEnded;
        public int DaysClaimed;
        public List<DailyReward> RewardsGranted;
        public ConfigData ConfigData;

        [Preserve]
        public DailyRewardsResult ()
        {
        }
    }
}