// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class ConfigData
    {
        public List<DailyReward> DailyRewards;
        public int SecondsPerDay;
        public int TotalDays;
        public List<DailyReward> BonusReward;

        [Preserve]
        public ConfigData ()
        {
        }
    }
}