// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class AreaData
    {
        public string AreaName;
        public int AreaLevel;
        public int CurrentProgress;
        public int MaxProgress;
        public int TotalUpgradableSlots;
        public int UnlockRequirement_Stars;
        public List<UpgradableAreaItem> UpgradableAreaItems;

        [Preserve]
        public AreaData ()
        {
        }
    }
}