// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class PlayerDataSyncResponse
    {
        public PlayerData PlayerData;
        public PlayerEconomyData EconomyData;
        public long LastUpdateTimestamp;

        [Preserve]
        public PlayerDataSyncResponse ()
        {
        }
    }
}