// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class UpgradableAreaItem
    {
        public string UpgradableName;
        public int UpgradableId;
        public bool IsUnlocked;
        public int CurrentLevel;
        public int MaxLevel;
        public int PerLevelCoinUpgradeRequirement;

        [Preserve]
        public UpgradableAreaItem ()
        {
        }
    }
}