// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class ProfilePicture
    {
        public string Type;
        public string ImageData;
        public int ImageId;

        [Preserve]
        public ProfilePicture ()
        {
        }
    }
}