// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class Reward
    {
        public string Service;
        public string Id;
        public int Amount;

        [Preserve]
        public Reward ()
        {
        }
    }
}