// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class Player
    {
        public string PlayerId;
        public string DisplayName;
        public ProfilePicture PlayerPortrait;

        [Preserve]
        public Player ()
        {
        }
    }
}