// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.GemHunterUGSCloud.Models
{
    public partial class LootBoxResult
    {
        public Dictionary<string,int> Currencies;
        public Dictionary<string,int> InventoryItems;

        [Preserve]
        public LootBoxResult ()
        {
        }
    }
}